POST http://localhost:3000/register
Content-Type: application/json
 
    {
        "full_name":"daiva rajackiene",
        "email":"daiva@daiva.lt",
        "password":"secret122"
    }

###

POST  http://localhost:3000/login
Content-Type: application/json

 {
    "email":"dai@dai.lt",
    "password":"secret122"
 }
###
POST  http://localhost:3000/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjQ3NDUwNzIzLCJleHAiOjE2NDc0NTQzMjN9.wj1DGB6JZw-PC-WRlhcK80-re39rO6LP8CoTJQydkFk
 {
    "group_id":1
 }

###
 
http://localhost:3000/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjQ3NDUwNzIzLCJleHAiOjE2NDc0NTQzMjN9.wj1DGB6JZw-PC-WRlhcK80-re39rO6LP8CoTJQydkFk
###

POST http://localhost:3000/bills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjQ3NDUwNzIzLCJleHAiOjE2NDc0NTQzMjN9.wj1DGB6JZw-PC-WRlhcK80-re39rO6LP8CoTJQydkFk

{
    "group_id":1,
    "amount": 200,
    "description": "drinks"
 }
###
GET http://localhost:3000/bills/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjQ3NDUwNzIzLCJleHAiOjE2NDc0NTQzMjN9.wj1DGB6JZw-PC-WRlhcK80-re39rO6LP8CoTJQydkFk
